wifi_ssid: "ENTER_YOUR_WIFI_NAME"
wifi_password: "ENTER_YOUR_WIFI_PASSWORD"
homey_address: "http://192.168.1.100"
homey_api_key: "ENTER_YOUR_HOMEY_API_TOKEN"
homey_charge_flow_id: "ENTER_THE_FLOW_ID"
